routes = {
    "home": "/",
    "about": "/about",
    "post": "/posts/{}",
    "latest": "/posts/latest",
    "new_post": "/posts/new",
    "post_edit": "/posts/{}/edit",
    "login": "/users/login",
    "signup": "/users/signup",
    "user": "/users/{}",
    "logout": "/users/logout",
    "user_posts": "/users/{}/posts",
    "user_edit": "/users/{}/edit",
    "user_liked_posts": "/users/{}/liked-posts",
    "user_following": "/users/{}/following",
    "user_followers": "/users/{}/followers",
    "change_password": "/settings/password",
    "search": "/search",
    "admin-dashboard": "/admin",
    "admin-punishments": "/admin/punishments",
    "admin-user": "/admin/users/{}",
    "admin-user-sessions": "/admin/users/{}/sessions",
    "admin-user-ban": "/admin/users/{}/ban",
    "admin-user-change-role": "/admin/users/{}/role",
    "admin-user-change-password": "/admin/users/{}/password",
    "admin-user-permaban": "/admin/users/{}/permaban",
    "admin-user-mute": "/admin/users/{}/mute",
    "admin-ip-ban": "/admin/ip/{}/ban",
    "admin-ip-mute": "/admin/ip/{}/mute"
}

API = {
    "like_post": "/api/posts/{}/like",
    "follow_user": "/api/users/{}/follow",
    "comment_post": "/api/posts/{}/comment",
    "reply_comment": "/api/comments/{}/reply",
}