# all urls for user-friendly endpoints with UI
routes = {
    "home": "/",
    "about": "/about",
    "post": "/posts/{}",
    "latest": "/posts/latest",
    "new_post": "/posts/new",
    "post_edit": "/posts/{}/edit",
    "login": "/users/login",
    "signup": "/users/signup",
    "user": "/users/{}",
    "users": "/users",
    "logout": "/users/logout",
    "user_posts": "/users/{}/posts",
    "image": "/images/{}",
    "user_edit": "/users/{}/edit",
    "user_liked_posts": "/users/{}/liked-posts",
    "user_following": "/users/{}/following",
    "user_followers": "/users/{}/followers",
    "change_password": "/settings/password",
    "search": "/search",
    "admin_dashboard": "/admin",
    "admin_config": "/admin/config",
    "admin_users": "/admin/users/",
    "admin_users_punished": "/admin/users/punished",
    "admin_user_sessions": "/admin/users/{}/sessions",
    "admin_user_punish": "/admin/users/{}/punish",
    "admin_user_censor_bio": "/admin/users/{}/censor",
    "admin_user_change_role": "/admin/users/{}/role",
    "admin_client_list": "/admin/clients/",
    "admin_client_sessions": "/admin/clients/{}/sessions",
    "admin_client_punish": "/admin/clients/{}/punish",
    "admin_post_delete": "/admin/posts/{}/delete",
    "admin_posts_pending": "/admin/posts/pending",
    "admin_post_approval": "/admin/posts/{}/approval",
    "admin_comment_delete": "/admin/comments/{}/delete",
    "admin_session_delete": "/admin/sessions/{}/delete",
}

# all urls for API endpoints that users do not directly interact with
API = {
    "like_post": "/api/posts/{}/like",
    "follow_user": "/api/users/{}/follow",
    "comment_post": "/api/posts/{}/comment",
    "reply_comment": "/api/comments/{}/reply",
}